services:
  php:
    build:
      context: .
      dockerfile: php/Dockerfile
    container_name: users-app
    volumes:
      - ../:/var/www
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      PHP_IDE_CONFIG: "serverName=docker-cli"

  nginx:
    image: "nginx:stable-alpine"
    container_name: users-nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ../public:/var/www/public
    depends_on:
      - php

  mysql:
    image: mysql:8.0
    container_name: users-db
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./storage:/var/lib/mysql
